### ISSUE TITLE
Netty Http2 instrumentation - Null checks in wrapped Http2Headers implementation

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#2024]
It looks like in certain (still unknown) configurations, the `Http2Headers` implementation that we wrap in our [Netty 4.1.16 module](https://github.com/newrelic/newrelic-java-agent/tree/main/instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116) isn't overriding the methods in AbstractHttp2Headers which throw `UnsupportedOperationException`

Specifically: `.method()` , `.path()`, `.authority()` and `.contains()`

To mitigate, a null check needs to be added in/around this [code](https://github.com/newrelic/newrelic-java-agent/blob/08bc501112a634e635e9cbe2754c085aa6020f50/instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/Http2RequestHeaderWrapper.java#L40) prior to de-referencing the wrapped `Http2Headers`.

[Internal slack thread](https://newrelic.slack.com/archives/C0NUYPJKA/p1724333515593749)

**Comment by kazablock** [comment]
Hi @jtduffy 

We are encountering a similar issue while using the Java Jetcd library in conjunction with the latest New Relic Java agent. Would it be possible to expedite a hotfix at the earliest ?

**Comment by jasonjkeller** [comment]
@kazablock There's a custom build of the Java agent jar that you can download here that I believe should fix this issue: https://github.com/newrelic/newrelic-java-agent/actions/runs/10725431981

Would you be willing to give it a try and verify that it does in fact resolve the issue for you? If it does, we'll make sure to get it into our next release.

**Comment by kazablock** [comment]
Thank You @jasonjkeller , now the error rate for nettydispatcher has become zero which was previously 100%. But the request.uri is always unknown. Looks like the root cause is not fixed. I am using jetcd-core:0.8.3

<img width="1156" alt="Screenshot 2024-09-06 at 4 38 27 PM" src="https://github.com/user-attachments/assets/32d11f85-3cf4-4304-9355-f08b98fe1048">

**Comment by jasonjkeller** [comment]
@kazablock The current behavior is expected as we don't explicitly have support for `grpc-netty` and it looks like we're probably going to need to create additional instrumentation for that. I've gone ahead and filed a feature request to add support for `grpc-netty`: https://github.com/newrelic/newrelic-java-agent/issues/2044

If you're able to provide a simple repro app using `jetcd-core:0.7.5`, it would certainly help to expedite this work. Thanks.

**Comment by kazablock** [comment]
Thank you @jasonjkeller , i have attached the reproducer. Running it is pretty straight forward.
Steps
1) Run etcd. (`docker compose up -d`)
2) create jar (`mvn clean package`)
3) run the jar with newrelic agent .(i have used the jar mentioned in this issue which has try catch added https://github.com/newrelic/newrelic-java-agent/actions/runs/10725431981) 
`java -javaagent:replaceme -Dnewrelic.config.app_name=replaceme -Dnewrelic.config.log_level=finest -Dnewrelic.config.log_file_name=STDOUT -Dnewrelic.config.license_key=replaceme -jar ./target/JetcdNewrelic-1.0-SNAPSHOT-jar-with-dependencies.jar`
4) check the console logs for error

**Comment by jasonjkeller** [comment]
Thanks again @kazablock ! I've copied the repro instructions over to the new issue for adding `grpc-netty` support. I'm closing out this issue as resolved and any future work on `grpc-netty` support will take place on https://github.com/newrelic/newrelic-java-agent/issues/2044.
